### ISSUE TITLE
can't import

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ghisguth/sunlight#2]
It insists I don't have Java, even though I can easily make apps using the IDE:

![image](https://user-images.githubusercontent.com/5357526/39401837-342be974-4b58-11e8-9565-abff35bdd64a.png)

**Comment by ghisguth** [comment]
Feel free to fix it and submit change

**Comment by AndroidDeveloperLB** [comment]
I tried. That's why I wrote this... :(

**Comment by nanderer** [comment]
try good old eclipse instead of that new strange studio thingy, i mean its an old app that existed before that ide

**Comment by AndroidDeveloperLB** [comment]
Wait, you can still do this?
Can you please put here an APK of it?

**Comment by nanderer** [comment]
apks can be found in the fdroid repository:

https://f-droid.org/de/packages/com.ghisguth.sun/

**Comment by AndroidDeveloperLB** [comment]
Oh thank you. Please consider putting this link with the logo of F-droid, on the main page of the repository.
